### ISSUE TITLE
Minor cosmetic issues

### ISSUE THREAD

**Issue by Zachar2** [HalianElf/Deluge-Dark#1]
Hi. Thanks for the eye-saving skin. I've found minor annoyances and I'm not sure if that's on my side or not. Here are the pics:

![2](https://user-images.githubusercontent.com/38113357/76630712-c4a9dc00-6540-11ea-86e5-37418d3a6431.png)

Thanks in advance for the answer.

Edit: Removed first picture as I found out it's a feature not a bug :)

**Comment by Hukuma1** [comment]
Heya. Great work on the theme. Looks much easier on the eyes.

Figured my issue is similar as above.

![delugedark](https://user-images.githubusercontent.com/54511555/81601499-d3b1dc80-937f-11ea-98a1-b0cf0c6b7908.gif)

All I did was drop in deluge.css over the previous one. vDeluge 2.0.3-2-201906121747-ubuntu18.04.1

**Comment by HalianElf** [comment]
I'm not sure why this wasn't automatically watched but I just saw these. Which version of Deluge @Zachar2? I'm on 2.0.4 and the labels are disappearing as they should be.

@Hukuma1 so you're not doing it as a subfilter? I never actually tested it to completely replace the original css.

**Comment by Zachar2** [comment]
@HalianElf I'm on Deluge 2.0.4.dev38. Yeah, labels do disappear but after logging in not before it. Sorry for the nitpicking but was just trying to calm my ocd.

**Comment by HalianElf** [comment]
Ah gotcha. Let me look into that. I have a js that logs me in automatically so could be why I never noticed it.

**Comment by HalianElf** [comment]
Should be good now @Zachar2

**Comment by Zachar2** [comment]
It is. Thank you :)
